### ISSUE TITLE
Path data/json does not exist in new install

### ISSUE THREAD

**Issue by willu47** [ClimateCompatibleGrowth/research_index_backend#5]
Error message:
```python
$ research_index data/d2d.txt 
  0%|                                                                                                                                                | 0/3 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/home/pi/mambaforge/envs/research_index/bin/research_index", line 8, in <module>
    sys.exit(entry_point())
             ^^^^^^^^^^^^^
  File "/home/pi/repositories/research_index_backend/src/research_index_backend/create_graph_from_doi.py", line 324, in entry_point
    result = main(list_of_dois, graph)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/repositories/research_index_backend/src/research_index_backend/create_graph_from_doi.py", line 257, in main
    metadata = get_output_metadata(session, valid_doi)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/repositories/research_index_backend/src/research_index_backend/create_graph_from_doi.py", line 104, in get_output_metadata
    with open(f"data/json/{clean_doi}.json", "w") as json_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'data/json/10.33774coe-2024-6l0rg.json'
```

**Comment by willu47** [comment]
Closed by #17
